vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /img
            upload_destination: '%kernel.project_dir%/public/img'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true


